# -*- coding: utf-8 -*-

import os
import sys
import time
import qtawesome
import threading
from PIL import Image
from PyQt5.QtGui import QPixmap, QCursor
from tkinter import filedialog
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import Qt, pyqtSignal, QTimer, QEvent
from PyQt5.QtWidgets import QFileDialog, QMainWindow, QTextEdit, QAction, QApplication
from tkinter import Tk
from tkinter.filedialog import askopenfilenames

from process import *

SCREEN_WEIGHT = 1920
SCREEN_HEIGHT = 1080
WINDOW_WEIGHT = 1200
WINDOW_HEIGHT = 700


class Ui_zhu(object):
    def setupUi(self, zhu):
        zhu.setObjectName("zhu")
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.Tool)  # 去掉标题栏
        self.stackedWidget = QtWidgets.QStackedWidget(zhu)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1200, 701))
        self.stackedWidget.setObjectName("stackedWidget")

        self.souye = QtWidgets.QWidget()
        self.souye.setObjectName("souye")

        self.label_SYBJ = QtWidgets.QLabel(self.souye)
        self.label_SYBJ.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.label_SYBJ.setStyleSheet("border-image: url(:/new/prefix1/image/zhu.png);")
        self.label_SYBJ.setObjectName("label_SYBJ")

        self.pushButton_SYGO = QtWidgets.QPushButton(self.souye)
        self.pushButton_SYGO.setGeometry(QtCore.QRect(548, 320, 100, 100))
        self.pushButton_SYGO.setStyleSheet("QPushButton{font-family:Microsoft Yahei; font-size:20pt; color:white; background-color:rgb(14 , 150 , 254);border-radius:50%;}\n"
"QPushButton:hover{background-color:rgb(44 , 137 , 255);}\n"
"QPushButton:pressed{background-color:rgb(14 , 135 , 228);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_SYGO.setObjectName("pushButton_SYGO")
        self.pushButton_SYDX = QtWidgets.QPushButton(self.souye)

        self.pushButton_SYDX.setGeometry(QtCore.QRect(560, 660, 75, 23))
        self.pushButton_SYDX.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:10pt;color:white;background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);}\n"
"QPushButton:hover{background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);}\n"
"QPushButton:pressed{background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);padding-left:2px;padding-top:2px;}\n"
"")
        self.pushButton_SYDX.setObjectName("pushButton_SYDX")
        self.pushButton_SYZXH = QtWidgets.QPushButton(self.souye)
        self.pushButton_SYZXH.setGeometry(QtCore.QRect(1100, 10, 20, 20))
        self.pushButton_SYZXH.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(85, 255, 127);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(58, 176, 86);}\n"
"QPushButton:pressed{background-color: rgb(1, 255, 18);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_SYZXH.setText("")
        self.pushButton_SYZXH.setObjectName("pushButton_SYZXH")
        self.pushButton_SYZXH.clicked.connect(self.aa_pushButton_ZXH)
        self.pushButton_SYQP = QtWidgets.QPushButton(self.souye)
        self.pushButton_SYQP.setGeometry(QtCore.QRect(1130, 10, 20, 20))
        self.pushButton_SYQP.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(214, 217, 23);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(191, 191, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_SYQP.setText("")
        self.pushButton_SYQP.setObjectName("pushButton_SYQP")
        self.pushButton_SYGB = QtWidgets.QPushButton(self.souye)
        self.pushButton_SYGB.clicked.connect(self.aa_pushButton_SYGB)
        self.pushButton_SYGB.setGeometry(QtCore.QRect(1160, 10, 20, 20))
        self.pushButton_SYGB.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(255, 94, 19);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(188, 0, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 0, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_SYGB.setText("")
        self.pushButton_SYGB.setObjectName("pushButton_SYGB")
        self.stackedWidget.addWidget(self.souye)
        self.xiangxi = QtWidgets.QWidget()
        self.xiangxi.setObjectName("xiangxi")
        self.label_bjxx = QtWidgets.QLabel(self.xiangxi)
        self.label_bjxx.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.label_bjxx.setStyleSheet("border-image: url(:/new/prefix1/image/bei.png);")
        self.label_bjxx.setText("")
        self.label_bjxx.setObjectName("label_bjxx")
        self.scrollArea_gd = QtWidgets.QScrollArea(self.xiangxi)
        self.scrollArea_gd.setGeometry(QtCore.QRect(230, 80, 760, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_gd.sizePolicy().hasHeightForWidth())
        self.scrollArea_gd.setSizePolicy(sizePolicy)
        self.scrollArea_gd.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_gd.setStyleSheet("QScrollArea{background-color: rgba(54, 62, 68, 0);border: 0px;border-radius: 0px;}\n"
"QScrollBar:vertical{margin:30px 0px 30px 0px;background-color: rgba(54, 62, 68, 0);border: 0px;width:15px;    }\n"
"QScrollBar::handle:vertical{background-color: rgb(39, 115, 230);width:15px;border-radius:7px;}\n"
"QScrollBar::handle:vertical:hover{background-color: rgb(30, 90, 180);width:15px;border-radius:7px;}\n"
"QScrollBar::add-line:vertical{subcontrol-origin: margin;border:1px solid rgb(117, 171, 253);height:15px;}\n"
"QScrollBar::sub-line:vertical{subcontrol-origin: margin; border:1px solid rgb(117, 171, 253);height:15px;}\n"
"QScrollBar::add-page:vertical{background-color:rgba(240,241,239, 0);}\n"
"QScrollBar::sub-page:vertical{background-color:rgba(240,241,239, 0); }\n"
"QScrollBar::up-arrow:vertical{border:1px solid rgb(117, 171, 253);width:15px;height:15px;}\n"
"QScrollBar::up-arrow:vertical:pressed{border:1px solid rgb(117, 171, 253);width:15px;height:15px;}\n"
"QScrollBar::down-arrow:vertical{ border:1px solid rgb(117, 171, 253);width:15px;height:15px;} \n"
"QScrollBar::down-arrow:vertical:pressed{border:1px solid rgb(117, 171, 253);width:15px;height:15px;}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{background:rgba(0,0,0,10%);border-radius:4px;}")
        self.scrollArea_gd.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_gd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_gd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_gd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_gd.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_gd.setWidgetResizable(True)
        self.scrollArea_gd.setObjectName("scrollArea_gd")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 745, 1100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(700, 1100))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_24SKBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKBJ.setGeometry(QtCore.QRect(0, 0, 730, 120))
        self.label_24SKBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_24SKBJ.setText("")
        self.label_24SKBJ.setObjectName("label_24SKBJ")
        self.label_24SKBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKBQ.setGeometry(QtCore.QRect(30, 30, 71, 51))
        self.label_24SKBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155253.png);")
        self.label_24SKBQ.setText("")
        self.label_24SKBQ.setObjectName("label_24SKBQ")
        self.label_24SKMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKMC.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.label_24SKMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                        "font: 10pt \"黑体\";")
        self.label_24SKMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24SKMC.setObjectName("label_24SKMC")
        self.label_OECFBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFBQ.setGeometry(QtCore.QRect(30, 150, 71, 51))
        self.label_OECFBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155208.png);")
        self.label_OECFBQ.setText("")
        self.label_OECFBQ.setObjectName("label_OECFBQ")
        self.label_OECFMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFMC.setGeometry(QtCore.QRect(30, 210, 71, 16))
        self.label_OECFMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                        "font: 10pt \"黑体\";")
        self.label_OECFMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OECFMC.setObjectName("label_OECFMC")
        self.label_OECFBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFBJ.setGeometry(QtCore.QRect(0, 120, 730, 120))
        self.label_OECFBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_OECFBJ.setText("")
        self.label_OECFBJ.setObjectName("label_OECFBJ")
        self.label_XIMENZIBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIBJ.setGeometry(QtCore.QRect(0, 240, 730, 120))
        self.label_XIMENZIBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_XIMENZIBJ.setText("")
        self.label_XIMENZIBJ.setObjectName("label_XIMENZIBJ")
        self.label_XIMENZIMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIMC.setGeometry(QtCore.QRect(30, 330, 71, 16))
        self.label_XIMENZIMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                           "font: 10pt \"黑体\";")
        self.label_XIMENZIMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_XIMENZIMC.setObjectName("label_XIMENZIMC")
        self.label_XIMENZIBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIBQ.setGeometry(QtCore.QRect(30, 270, 71, 51))
        self.label_XIMENZIBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155227.png);")
        self.label_XIMENZIBQ.setText("")
        self.label_XIMENZIBQ.setObjectName("label_XIMENZIBQ")
        self.label_FENBIANLVMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLVMC.setGeometry(QtCore.QRect(30, 450, 71, 16))
        self.label_FENBIANLVMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                             "font: 10pt \"黑体\";")
        self.label_FENBIANLVMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FENBIANLVMC.setObjectName("label_FENBIANLVMC")
        self.label_FENBIANLVBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLVBQ.setGeometry(QtCore.QRect(30, 390, 71, 51))
        self.label_FENBIANLVBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155304.png);")
        self.label_FENBIANLVBQ.setText("")
        self.label_FENBIANLVBQ.setObjectName("label_FENBIANLVBQ")
        self.label_FENBIANLVBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLVBJ.setGeometry(QtCore.QRect(0, 360, 730, 120))
        self.label_FENBIANLVBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_FENBIANLVBJ.setText("")
        self.label_FENBIANLVBJ.setObjectName("label_FENBIANLVBJ")
        self.label_DNPMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPMC.setGeometry(QtCore.QRect(30, 570, 71, 16))
        self.label_DNPMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                       "font: 10pt \"黑体\";")
        self.label_DNPMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DNPMC.setObjectName("label_DNPMC")
        self.label_DNPBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPBQ.setGeometry(QtCore.QRect(30, 510, 71, 51))
        self.label_DNPBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155313.png);")
        self.label_DNPBQ.setText("")
        self.label_DNPBQ.setObjectName("label_DNPBQ")
        self.label_DNPBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPBJ.setGeometry(QtCore.QRect(0, 480, 730, 120))
        self.label_DNPBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_DNPBJ.setText("")
        self.label_DNPBJ.setObjectName("label_DNPBJ")
        self.label_GPGRMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGRMC.setGeometry(QtCore.QRect(30, 690, 71, 16))
        self.label_GPGRMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                        "font: 10pt \"黑体\";")
        self.label_GPGRMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPGRMC.setObjectName("label_GPGRMC")
        self.label_GPGRBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGRBQ.setGeometry(QtCore.QRect(30, 630, 71, 51))
        self.label_GPGRBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155321.png);")
        self.label_GPGRBQ.setText("")
        self.label_GPGRBQ.setObjectName("label_GPGRBQ")
        self.label_GPGRBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGRBJ.setGeometry(QtCore.QRect(0, 600, 730, 120))
        self.label_GPGRBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_GPGRBJ.setText("")
        self.label_GPGRBJ.setObjectName("label_GPGRBJ")
        self.label_HUIJIEMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEMC.setGeometry(QtCore.QRect(30, 810, 71, 16))
        self.label_HUIJIEMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                          "font: 10pt \"黑体\";")
        self.label_HUIJIEMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HUIJIEMC.setObjectName("label_HUIJIEMC")
        self.label_HUIJIEBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEBJ.setGeometry(QtCore.QRect(0, 720, 730, 120))
        self.label_HUIJIEBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_HUIJIEBJ.setText("")
        self.label_HUIJIEBJ.setObjectName("label_HUIJIEBJ")
        self.label_HUIJIEBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEBQ.setGeometry(QtCore.QRect(30, 750, 71, 51))
        self.label_HUIJIEBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155332.png);")
        self.label_HUIJIEBQ.setText("")
        self.label_HUIJIEBQ.setObjectName("label_HUIJIEBQ")
        self.label_DZTBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTBJ.setGeometry(QtCore.QRect(0, 840, 730, 120))
        self.label_DZTBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_DZTBJ.setText("")
        self.label_DZTBJ.setObjectName("label_DZTBJ")
        self.label_DZTBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTBQ.setGeometry(QtCore.QRect(30, 870, 71, 51))
        self.label_DZTBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155340.png);")
        self.label_DZTBQ.setText("")
        self.label_DZTBQ.setObjectName("label_DZTBQ")
        self.label_DZTMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTMC.setGeometry(QtCore.QRect(30, 930, 71, 16))
        self.label_DZTMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                       "font: 10pt \"黑体\";")
        self.label_DZTMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DZTMC.setObjectName("label_DZTMC")
        self.label_KYTBJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTBJ.setGeometry(QtCore.QRect(0, 960, 730, 120))
        self.label_KYTBJ.setStyleSheet("border-image: url(:/new/prefix1/image/lie.png);")
        self.label_KYTBJ.setText("")
        self.label_KYTBJ.setObjectName("label_KYTBJ")
        self.label_KYTBQ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTBQ.setGeometry(QtCore.QRect(30, 990, 71, 51))
        self.label_KYTBQ.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155244.png);")
        self.label_KYTBQ.setText("")
        self.label_KYTBQ.setObjectName("label_KYTBQ")
        self.label_KYTMC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTMC.setGeometry(QtCore.QRect(30, 1050, 71, 16))
        self.label_KYTMC.setStyleSheet("color: rgb(85, 255, 255);\n"
                                       "font: 10pt \"黑体\";")
        self.label_KYTMC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_KYTMC.setObjectName("label_KYTMC")
        self.label_24SKXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_1.setGeometry(QtCore.QRect(130, 20, 68, 90))
        #self.label_24SKXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_1.setText("")
        self.label_24SKXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_1.setObjectName("label_24SKXS_1")
        self.label_24SKXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_2.setGeometry(QtCore.QRect(210, 20, 68, 90))
        #self.label_24SKXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_2.setText("")
        self.label_24SKXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_2.setObjectName("label_24SKXS_2")
        self.label_24SKXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_3.setGeometry(QtCore.QRect(290, 20, 68, 90))
       # self.label_24SKXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_3.setText("")
        self.label_24SKXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_3.setObjectName("label_24SKXS_3")
        self.label_24SKXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_4.setGeometry(QtCore.QRect(370, 20, 68, 90))
        #self.label_24SKXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_4.setText("")
        self.label_24SKXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_4.setObjectName("label_24SKXS_4")
        self.label_24SKXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_5.setGeometry(QtCore.QRect(450, 20, 68, 90))
        #self.label_24SKXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_5.setText("")
        self.label_24SKXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_5.setObjectName("label_24SKXS_5")
        self.label_OECFXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_5.setGeometry(QtCore.QRect(450, 140, 68, 90))
        #self.label_OECFXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_5.setText("")
        self.label_OECFXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_5.setObjectName("label_OECFXS_5")
        self.label_OECFXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_1.setGeometry(QtCore.QRect(130, 140, 68, 90))
        #self.label_OECFXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_1.setText("")
        self.label_OECFXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_1.setObjectName("label_OECFXS_1")
        self.label_OECFXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_4.setGeometry(QtCore.QRect(370, 140, 68, 90))
        #self.label_OECFXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_4.setText("")
        self.label_OECFXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_4.setObjectName("label_OECFXS_4")
        self.label_OECFXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_3.setGeometry(QtCore.QRect(290, 140, 68, 90))
        #self.label_OECFXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_3.setText("")
        self.label_OECFXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_3.setObjectName("label_OECFXS_3")
        self.label_OECFXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_2.setGeometry(QtCore.QRect(210, 140, 68, 90))
        #self.label_OECFXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_2.setText("")
        self.label_OECFXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_2.setObjectName("label_OECFXS_2")
        self.label_FENBIANLV_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_1.setGeometry(QtCore.QRect(130, 380, 68, 90))
        #self.label_FENBIANLV_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_1.setText("")
        self.label_FENBIANLV_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_1.setObjectName("label_FENBIANLV_1")
        self.label_XIMENZIXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_5.setGeometry(QtCore.QRect(450, 260, 68, 90))
        #self.label_XIMENZIXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_5.setText("")
        self.label_XIMENZIXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_5.setObjectName("label_XIMENZIXS_5")
        self.label_FENBIANLV_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_3.setGeometry(QtCore.QRect(290, 380, 68, 90))
        #self.label_FENBIANLV_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_3.setText("")
        self.label_FENBIANLV_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_3.setObjectName("label_FENBIANLV_3")
        self.label_XIMENZIXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_1.setGeometry(QtCore.QRect(130, 260, 68, 90))
        #self.label_XIMENZIXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_1.setText("")
        self.label_XIMENZIXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_1.setObjectName("label_XIMENZIXS_1")
        self.label_XIMENZIXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_4.setGeometry(QtCore.QRect(370, 260, 68, 90))
        #self.label_XIMENZIXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_4.setText("")
        self.label_XIMENZIXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_4.setObjectName("label_XIMENZIXS_4")
        self.label_XIMENZIXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_3.setGeometry(QtCore.QRect(290, 260, 68, 90))
        #self.label_XIMENZIXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_3.setText("")
        self.label_XIMENZIXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_3.setObjectName("label_XIMENZIXS_3")
        self.label_FENBIANLV_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_4.setGeometry(QtCore.QRect(370, 380, 68, 90))
        #self.label_FENBIANLV_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_4.setText("")
        self.label_FENBIANLV_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_4.setObjectName("label_FENBIANLV_4")
        self.label_FENBIANLV_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_2.setGeometry(QtCore.QRect(210, 380, 68, 90))
        #self.label_FENBIANLV_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_2.setText("")
        self.label_FENBIANLV_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_2.setObjectName("label_FENBIANLV_2")
        self.label_XIMENZIXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_2.setGeometry(QtCore.QRect(210, 260, 68, 90))
        #self.label_XIMENZIXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_2.setText("")
        self.label_XIMENZIXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_2.setObjectName("label_XIMENZIXS_2")
        self.label_FENBIANLV_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_5.setGeometry(QtCore.QRect(450, 380, 68, 90))
        #self.label_FENBIANLV_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_5.setText("")
        self.label_FENBIANLV_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_5.setObjectName("label_FENBIANLV_5")
        self.label_DNPXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_1.setGeometry(QtCore.QRect(130, 500, 68, 90))
        #self.label_DNPXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_1.setText("")
        self.label_DNPXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_1.setObjectName("label_DNPXS_1")
        self.label_DNPXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_5.setGeometry(QtCore.QRect(450, 500, 68, 90))
        #self.label_DNPXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_5.setText("")
        self.label_DNPXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_5.setObjectName("label_DNPXS_5")
        self.label_DNPXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_3.setGeometry(QtCore.QRect(290, 500, 68, 90))
        #self.label_DNPXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_3.setText("")
        self.label_DNPXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_3.setObjectName("label_DNPXS_3")
        self.label_DNPXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_2.setGeometry(QtCore.QRect(210, 500, 68, 90))
        #self.label_DNPXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_2.setText("")
        self.label_DNPXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_2.setObjectName("label_DNPXS_2")
        self.label_DNPXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_4.setGeometry(QtCore.QRect(370, 500, 68, 90))
        #self.label_DNPXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_4.setText("")
        self.label_DNPXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_4.setObjectName("label_DNPXS_4")
        self.label_GPGR_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_1.setGeometry(QtCore.QRect(130, 620, 68, 90))
        #self.label_GPGR_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_1.setText("")
        self.label_GPGR_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_1.setObjectName("label_GPGR_1")
        self.label_GPGR_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_5.setGeometry(QtCore.QRect(450, 620, 68, 90))
       # self.label_GPGR_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_5.setText("")
        self.label_GPGR_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_5.setObjectName("label_GPGR_5")
        self.label_HUIJIEXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_5.setGeometry(QtCore.QRect(450, 740, 68, 90))
        #self.label_HUIJIEXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_5.setText("")
        self.label_HUIJIEXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_5.setObjectName("label_HUIJIEXS_5")
        self.label_KYTXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_3.setGeometry(QtCore.QRect(290, 980, 68, 90))
        #self.label_KYTXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_3.setText("")
        self.label_KYTXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_3.setObjectName("label_KYTXS_3")
        self.label_HUIJIEXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_1.setGeometry(QtCore.QRect(130, 740, 68, 90))
        #self.label_HUIJIEXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_1.setText("")
        self.label_HUIJIEXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_1.setObjectName("label_HUIJIEXS_1")
        self.label_HUIJIEXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_3.setGeometry(QtCore.QRect(290, 740, 68, 90))
        #self.label_HUIJIEXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_3.setText("")
        self.label_HUIJIEXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_3.setObjectName("label_HUIJIEXS_3")
        self.label_KYTXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_5.setGeometry(QtCore.QRect(450, 980, 68, 90))
        #self.label_KYTXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_5.setText("")
        self.label_KYTXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_5.setObjectName("label_KYTXS_5")
        self.label_GPGR_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_3.setGeometry(QtCore.QRect(290, 620, 68, 90))
        #self.label_GPGR_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_3.setText("")
        self.label_GPGR_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_3.setObjectName("label_GPGR_3")
        self.label_HUIJIEXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_2.setGeometry(QtCore.QRect(210, 740, 68, 90))
        #self.label_HUIJIEXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_2.setText("")
        self.label_HUIJIEXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_2.setObjectName("label_HUIJIEXS_2")
        self.label_DZTXS_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_5.setGeometry(QtCore.QRect(450, 860, 68, 90))
        #self.label_DZTXS_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_5.setText("")
        self.label_DZTXS_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_5.setObjectName("label_DZTXS_5")
        self.label_KYTXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_2.setGeometry(QtCore.QRect(210, 980, 68, 90))
        #self.label_KYTXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_2.setText("")
        self.label_KYTXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_2.setObjectName("label_KYTXS_2")
        self.label_HUIJIEXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_4.setGeometry(QtCore.QRect(370, 740, 68, 90))
        #self.label_HUIJIEXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_4.setText("")
        self.label_HUIJIEXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_4.setObjectName("label_HUIJIEXS_4")
        self.label_GPGR_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_2.setGeometry(QtCore.QRect(210, 620, 68, 90))
        #self.label_GPGR_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_2.setText("")
        self.label_GPGR_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_2.setObjectName("label_GPGR_2")
        self.label_DZTXS_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_2.setGeometry(QtCore.QRect(210, 860, 68, 90))
        #self.label_DZTXS_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_2.setText("")
        self.label_DZTXS_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_2.setObjectName("label_DZTXS_2")
        self.label_DZTXS_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_3.setGeometry(QtCore.QRect(290, 860, 68, 90))
        #self.label_DZTXS_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_3.setText("")
        self.label_DZTXS_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_3.setObjectName("label_DZTXS_3")
        self.label_DZTXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_4.setGeometry(QtCore.QRect(370, 860, 68, 90))
        #self.label_DZTXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_4.setText("")
        self.label_DZTXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_4.setObjectName("label_DZTXS_4")
        self.label_KYTXS_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_4.setGeometry(QtCore.QRect(370, 980, 68, 90))
        #self.label_KYTXS_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_4.setText("")
        self.label_KYTXS_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_4.setObjectName("label_KYTXS_4")
        self.label_DZTXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_1.setGeometry(QtCore.QRect(130, 860, 68, 90))
        #self.label_DZTXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_1.setText("")
        self.label_DZTXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_1.setObjectName("label_DZTXS_1")
        self.label_KYTXS_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_1.setGeometry(QtCore.QRect(130, 980, 68, 90))
        #self.label_KYTXS_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_1.setText("")
        self.label_KYTXS_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_1.setObjectName("label_KYTXS_1")
        self.label_GPGR_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_4.setGeometry(QtCore.QRect(370, 620, 68, 90))
        #self.label_GPGR_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_4.setText("")
        self.label_GPGR_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_4.setObjectName("label_GPGR_4")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(680, 50, 41, 23))
        self.pushButton.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}\n")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label_24SKXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_6.setGeometry(QtCore.QRect(530, 20, 68, 90))
       # self.label_24SKXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_6.setText("")
        self.label_24SKXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_6.setObjectName("label_24SKXS_6")
        self.label_24SKXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24SKXS_7.setGeometry(QtCore.QRect(610, 20, 68, 90))
        #self.label_24SKXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_24SKXS_7.setText("")
        self.label_24SKXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_24SKXS_7.setObjectName("label_24SKXS_7")
        self.label_OECFXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_6.setGeometry(QtCore.QRect(530, 140, 68, 90))
        #self.label_OECFXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_6.setText("")
        self.label_OECFXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_6.setObjectName("label_OECFXS_6")
        self.label_OECFXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_OECFXS_7.setGeometry(QtCore.QRect(610, 140, 68, 90))
        #self.label_OECFXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_OECFXS_7.setText("")
        self.label_OECFXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_OECFXS_7.setObjectName("label_OECFXS_7")
        self.label_XIMENZIXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_6.setGeometry(QtCore.QRect(530, 260, 68, 90))
        #self.label_XIMENZIXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_6.setText("")
        self.label_XIMENZIXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_6.setObjectName("label_XIMENZIXS_6")
        self.label_XIMENZIXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_XIMENZIXS_7.setGeometry(QtCore.QRect(610, 260, 68, 90))
        #self.label_XIMENZIXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_XIMENZIXS_7.setText("")
        self.label_XIMENZIXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_XIMENZIXS_7.setObjectName("label_XIMENZIXS_7")
        self.label_FENBIANLV_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_6.setGeometry(QtCore.QRect(530, 380, 68, 90))
        #self.label_FENBIANLV_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_6.setText("")
        self.label_FENBIANLV_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_6.setObjectName("label_FENBIANLV_6")
        self.label_FENBIANLV_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_FENBIANLV_7.setGeometry(QtCore.QRect(610, 380, 68, 90))
        #self.label_FENBIANLV_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_FENBIANLV_7.setText("")
        self.label_FENBIANLV_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_FENBIANLV_7.setObjectName("label_FENBIANLV_7")
        self.label_DNPXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_6.setGeometry(QtCore.QRect(530, 500, 68, 90))
        #self.label_DNPXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_6.setText("")
        self.label_DNPXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_6.setObjectName("label_DNPXS_6")
        self.label_DNPXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DNPXS_7.setGeometry(QtCore.QRect(610, 500, 68, 90))
        #self.label_DNPXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DNPXS_7.setText("")
        self.label_DNPXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DNPXS_7.setObjectName("label_DNPXS_7")
        self.label_KYTXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_6.setGeometry(QtCore.QRect(530, 980, 68, 90))
        #self.label_KYTXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_6.setText("")
        self.label_KYTXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_6.setObjectName("label_KYTXS_6")
        self.label_HUIJIEXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_6.setGeometry(QtCore.QRect(530, 740, 68, 90))
        #self.label_HUIJIEXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_6.setText("")
        self.label_HUIJIEXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_6.setObjectName("label_HUIJIEXS_6")
        self.label_DZTXS_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_6.setGeometry(QtCore.QRect(530, 860, 68, 90))
        #self.label_DZTXS_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_6.setText("")
        self.label_DZTXS_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_6.setObjectName("label_DZTXS_6")
        self.label_GPGR_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_6.setGeometry(QtCore.QRect(530, 620, 68, 90))
        #self.label_GPGR_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_6.setText("")
        self.label_GPGR_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_6.setObjectName("label_GPGR_6")
        self.label_KYTXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_KYTXS_7.setGeometry(QtCore.QRect(610, 980, 68, 90))
        #self.label_KYTXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_KYTXS_7.setText("")
        self.label_KYTXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_KYTXS_7.setObjectName("label_KYTXS_7")
        self.label_GPGR_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_GPGR_7.setGeometry(QtCore.QRect(610, 620, 68, 90))
        #self.label_GPGR_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_GPGR_7.setText("")
        self.label_GPGR_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_GPGR_7.setObjectName("label_GPGR_7")
        self.label_HUIJIEXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_HUIJIEXS_7.setGeometry(QtCore.QRect(610, 740, 68, 90))
        #self.label_HUIJIEXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_HUIJIEXS_7.setText("")
        self.label_HUIJIEXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_HUIJIEXS_7.setObjectName("label_HUIJIEXS_7")
        self.label_DZTXS_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_DZTXS_7.setGeometry(QtCore.QRect(610, 860, 68, 90))
        #self.label_DZTXS_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_DZTXS_7.setText("")
        self.label_DZTXS_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_DZTXS_7.setObjectName("label_DZTXS_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(680, 180, 41, 23))
        self.pushButton_2.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 300, 41, 23))
        self.pushButton_3.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 410, 41, 23))
        self.pushButton_4.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 530, 41, 23))
        self.pushButton_5.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 650, 41, 23))
        self.pushButton_6.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(680, 770, 41, 23))
        self.pushButton_7.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(680, 890, 41, 23))
        self.pushButton_8.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(680, 1010, 41, 23))
        self.pushButton_9.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:13pt;color: rgb(0, 255, 255);}\n"
"QPushButton:hover{}\n"
"QPushButton:pressed{padding-left:3px; padding-top:3px;}")
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_HUIJIEBJ.raise_()
        self.label_GPGRBJ.raise_()
        self.label_DNPBJ.raise_()
        self.label_FENBIANLVBJ.raise_()
        self.label_OECFBJ.raise_()
        self.label_24SKBJ.raise_()
        self.label_24SKBQ.raise_()
        self.label_24SKMC.raise_()
        self.label_OECFBQ.raise_()
        self.label_OECFMC.raise_()
        self.label_XIMENZIBJ.raise_()
        self.label_XIMENZIMC.raise_()
        self.label_XIMENZIBQ.raise_()
        self.label_FENBIANLVMC.raise_()
        self.label_FENBIANLVBQ.raise_()
        self.label_DNPMC.raise_()
        self.label_DNPBQ.raise_()
        self.label_GPGRMC.raise_()
        self.label_GPGRBQ.raise_()
        self.label_HUIJIEMC.raise_()
        self.label_HUIJIEBQ.raise_()
        self.label_DZTBJ.raise_()
        self.label_DZTBQ.raise_()
        self.label_DZTMC.raise_()
        self.label_KYTBJ.raise_()
        self.label_KYTBQ.raise_()
        self.label_KYTMC.raise_()
        self.label_24SKXS_1.raise_()
        self.label_24SKXS_2.raise_()
        self.label_24SKXS_3.raise_()
        self.label_24SKXS_4.raise_()
        self.label_24SKXS_5.raise_()
        self.label_OECFXS_5.raise_()
        self.label_OECFXS_1.raise_()
        self.label_OECFXS_4.raise_()
        self.label_OECFXS_3.raise_()
        self.label_OECFXS_2.raise_()
        self.label_FENBIANLV_1.raise_()
        self.label_XIMENZIXS_5.raise_()
        self.label_FENBIANLV_3.raise_()
        self.label_XIMENZIXS_1.raise_()
        self.label_XIMENZIXS_4.raise_()
        self.label_XIMENZIXS_3.raise_()
        self.label_FENBIANLV_4.raise_()
        self.label_FENBIANLV_2.raise_()
        self.label_XIMENZIXS_2.raise_()
        self.label_FENBIANLV_5.raise_()
        self.label_DNPXS_1.raise_()
        self.label_DNPXS_5.raise_()
        self.label_DNPXS_3.raise_()
        self.label_DNPXS_2.raise_()
        self.label_DNPXS_4.raise_()
        self.label_GPGR_1.raise_()
        self.label_GPGR_5.raise_()
        self.label_HUIJIEXS_5.raise_()
        self.label_KYTXS_3.raise_()
        self.label_HUIJIEXS_1.raise_()
        self.label_HUIJIEXS_3.raise_()
        self.label_KYTXS_5.raise_()
        self.label_GPGR_3.raise_()
        self.label_HUIJIEXS_2.raise_()
        self.label_DZTXS_5.raise_()
        self.label_KYTXS_2.raise_()
        self.label_HUIJIEXS_4.raise_()
        self.label_GPGR_2.raise_()
        self.label_DZTXS_2.raise_()
        self.label_DZTXS_3.raise_()
        self.label_DZTXS_4.raise_()
        self.label_KYTXS_4.raise_()
        self.label_DZTXS_1.raise_()
        self.label_KYTXS_1.raise_()
        self.label_GPGR_4.raise_()
        self.pushButton.raise_()
        self.label_24SKXS_6.raise_()
        self.label_24SKXS_7.raise_()
        self.label_OECFXS_6.raise_()
        self.label_OECFXS_7.raise_()
        self.label_XIMENZIXS_6.raise_()
        self.label_XIMENZIXS_7.raise_()
        self.label_FENBIANLV_6.raise_()
        self.label_FENBIANLV_7.raise_()
        self.label_DNPXS_6.raise_()
        self.label_DNPXS_7.raise_()
        self.label_KYTXS_6.raise_()
        self.label_HUIJIEXS_6.raise_()
        self.label_DZTXS_6.raise_()
        self.label_GPGR_6.raise_()
        self.label_KYTXS_7.raise_()
        self.label_GPGR_7.raise_()
        self.label_HUIJIEXS_7.raise_()
        self.label_DZTXS_7.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.scrollArea_gd.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_XXQD = QtWidgets.QPushButton(self.xiangxi)
        self.pushButton_XXQD.setGeometry(QtCore.QRect(540, 660, 111, 31))
        self.pushButton_XXQD.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:10pt;color:white; background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);}\n"
"QPushButton:hover{ background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);}\n"
"QPushButton:pressed{background-color:rgb(14 , 150 , 254, 0);border-image: url(:/new/prefix1/image/an.png);padding-left:2px;padding-top:2px;}\n"
"")
        self.pushButton_XXQD.setObjectName("pushButton_XXQD")
        self.label_XXDJS = QtWidgets.QLabel(self.xiangxi)
        self.label_XXDJS.setGeometry(QtCore.QRect(570, 630, 51, 31))
        self.label_XXDJS.setStyleSheet("color: rgb(85, 255, 255);\n"
                                       "font: 20pt \"黑体\";")
        self.label_XXDJS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_XXDJS.setObjectName("label_XXDJS")
        self.pushButton_XXGB = QtWidgets.QPushButton(self.xiangxi)
        self.pushButton_XXGB.setGeometry(QtCore.QRect(1160, 10, 20, 20))
        self.pushButton_XXGB.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(255, 94, 19);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(188, 0, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 0, 0);padding-left:3px;padding-top:3px;}\n")
        self.pushButton_XXGB.setText("")
        self.pushButton_XXGB.setObjectName("pushButton_XXGB")
        self.pushButton_XXGB.clicked.connect(self.aa_pushButton_SYGB)
        self.pushButton_XXQP = QtWidgets.QPushButton(self.xiangxi)
        self.pushButton_XXQP.setGeometry(QtCore.QRect(1130, 10, 20, 20))
        self.pushButton_XXQP.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(214, 217, 23);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(191, 191, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 0);padding-left:3px;padding-top:3px;}\n")
        self.pushButton_XXQP.setText("")
        self.pushButton_XXQP.setObjectName("pushButton_XXQP")
        self.pushButton_XXZXH = QtWidgets.QPushButton(self.xiangxi)
        self.pushButton_XXZXH.setGeometry(QtCore.QRect(1100, 10, 20, 20))
        self.pushButton_XXZXH.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(85, 255, 127);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(58, 176, 86);}\n"
"QPushButton:pressed{background-color: rgb(1, 255, 18);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_XXZXH.setText("")
        self.pushButton_XXZXH.setObjectName("pushButton_XXZXH")
        self.pushButton_XXZXH.clicked.connect(self.aa_pushButton_ZXH)
        self.stackedWidget.addWidget(self.xiangxi)
        self.xianshi = QtWidgets.QWidget()
        self.xianshi.setObjectName("xianshi")
        self.label = QtWidgets.QLabel(self.xianshi)
        self.label.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.label.setStyleSheet("border-image: url(:/new/prefix1/image/bei.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_XS1 = QtWidgets.QLabel(self.xianshi)
        self.label_XS1.setGeometry(QtCore.QRect(140, 110, 200, 170))
        self.label_XS1.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS1.setText("")
        self.label_XS1.setObjectName("label_XS1")
        self.label_XS2 = QtWidgets.QLabel(self.xianshi)
        self.label_XS2.setGeometry(QtCore.QRect(370, 110, 200, 170))
        self.label_XS2.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS2.setText("")
        self.label_XS2.setObjectName("label_XS2")
        self.label_XS3 = QtWidgets.QLabel(self.xianshi)
        self.label_XS3.setGeometry(QtCore.QRect(610, 110, 200, 170))
        self.label_XS3.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS3.setText("")
        self.label_XS3.setObjectName("label_XS3")
        self.label_XS4 = QtWidgets.QLabel(self.xianshi)
        self.label_XS4.setGeometry(QtCore.QRect(850, 110, 200, 170))
        self.label_XS4.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS4.setText("")
        self.label_XS4.setObjectName("label_XS4")
        self.label_XS8 = QtWidgets.QLabel(self.xianshi)
        self.label_XS8.setGeometry(QtCore.QRect(850, 290, 200, 170))
        self.label_XS8.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS8.setText("")
        self.label_XS8.setObjectName("label_XS8")
        self.label_XS10 = QtWidgets.QLabel(self.xianshi)
        self.label_XS10.setGeometry(QtCore.QRect(370, 470, 200, 170))
        self.label_XS10.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS10.setText("")
        self.label_XS10.setObjectName("label_XS10")
        self.label_XS6 = QtWidgets.QLabel(self.xianshi)
        self.label_XS6.setGeometry(QtCore.QRect(370, 290, 200, 170))
        self.label_XS6.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS6.setText("")
        self.label_XS6.setObjectName("label_XS6")
        self.label_XS7 = QtWidgets.QLabel(self.xianshi)
        self.label_XS7.setGeometry(QtCore.QRect(610, 290, 200, 170))
        self.label_XS7.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS7.setText("")
        self.label_XS7.setObjectName("label_XS7")
        self.label_XS9 = QtWidgets.QLabel(self.xianshi)
        self.label_XS9.setGeometry(QtCore.QRect(140, 470, 200, 170))
        self.label_XS9.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS9.setText("")
        self.label_XS9.setObjectName("label_XS9")
        self.label_XS5 = QtWidgets.QLabel(self.xianshi)
        self.label_XS5.setGeometry(QtCore.QRect(140, 290, 200, 170))
        self.label_XS5.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS5.setText("")
        self.label_XS5.setObjectName("label_XS5")
        self.label_XS13 = QtWidgets.QLabel(self.xianshi)
        self.label_XS13.setGeometry(QtCore.QRect(850, 470, 200, 170))
        self.label_XS13.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS13.setText("")
        self.label_XS13.setObjectName("label_XS13")
        self.label_XS11 = QtWidgets.QLabel(self.xianshi)
        self.label_XS11.setGeometry(QtCore.QRect(610, 470, 200, 170))
        self.label_XS11.setStyleSheet("image: url(:/new/prefix1/image/xsk.png);")
        self.label_XS11.setText("")
        self.label_XS11.setObjectName("label_XS11")
        self.label_DZTBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_DZTBQ_2.setGeometry(QtCore.QRect(855, 320, 190, 130))
        self.label_DZTBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155340.png);")
        self.label_DZTBQ_2.setText("")
        self.label_DZTBQ_2.setObjectName("label_DZTBQ_2")
        self.label_24SKBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_24SKBQ_2.setGeometry(QtCore.QRect(145, 140, 190, 130))
        self.label_24SKBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155253.png);")
        self.label_24SKBQ_2.setText("")
        self.label_24SKBQ_2.setObjectName("label_24SKBQ_2")
        self.label_XIMENZIBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_XIMENZIBQ_2.setGeometry(QtCore.QRect(615, 140, 190, 130))
        self.label_XIMENZIBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155227.png);")
        self.label_XIMENZIBQ_2.setText("")
        self.label_XIMENZIBQ_2.setObjectName("label_XIMENZIBQ_2")
        self.label_FENBIANLVBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_FENBIANLVBQ_2.setGeometry(QtCore.QRect(855, 140, 190, 130))
        self.label_FENBIANLVBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155304.png);")
        self.label_FENBIANLVBQ_2.setText("")
        self.label_FENBIANLVBQ_2.setObjectName("label_FENBIANLVBQ_2")
        self.label_DNPBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_DNPBQ_2.setGeometry(QtCore.QRect(145, 320, 190, 130))
        self.label_DNPBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155313.png);")
        self.label_DNPBQ_2.setText("")
        self.label_DNPBQ_2.setObjectName("label_DNPBQ_2")
        self.label_HUIJIEBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_HUIJIEBQ_2.setGeometry(QtCore.QRect(615, 320, 190, 130))
        self.label_HUIJIEBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155332.png);")
        self.label_HUIJIEBQ_2.setText("")
        self.label_HUIJIEBQ_2.setObjectName("label_HUIJIEBQ_2")
        self.label_GPGRBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_GPGRBQ_2.setGeometry(QtCore.QRect(375, 320, 190, 130))
        self.label_GPGRBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155321.png);")
        self.label_GPGRBQ_2.setText("")
        self.label_GPGRBQ_2.setObjectName("label_GPGRBQ_2")
        self.label_OECFBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_OECFBQ_2.setGeometry(QtCore.QRect(375, 140, 190, 130))
        self.label_OECFBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155208.png);")
        self.label_OECFBQ_2.setText("")
        self.label_OECFBQ_2.setObjectName("label_OECFBQ_2")
        self.label_KYTBQ_2 = QtWidgets.QLabel(self.xianshi)
        self.label_KYTBQ_2.setGeometry(QtCore.QRect(145, 500, 190, 130))
        self.label_KYTBQ_2.setStyleSheet("border-image: url(:/new/prefix1/image/20200728155244.png);")
        self.label_KYTBQ_2.setText("")
        self.label_KYTBQ_2.setObjectName("label_KYTBQ_2")
        self.pushButton_XSGB = QtWidgets.QPushButton(self.xianshi)
        self.pushButton_XSGB.setGeometry(QtCore.QRect(1160, 10, 20, 20))
        self.pushButton_XSGB.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(255, 94, 19);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(188, 0, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 0, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_XSGB.setText("")
        self.pushButton_XSGB.setObjectName("pushButton_XSGB")
        self.pushButton_XSGB.clicked.connect(self.aa_pushButton_SYGB)
        self.pushButton_XSQP = QtWidgets.QPushButton(self.xianshi)
        self.pushButton_XSQP.setGeometry(QtCore.QRect(1130, 10, 20, 20))
        self.pushButton_XSQP.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(214, 217, 23);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(191, 191, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_XSQP.setText("")
        self.pushButton_XSQP.setObjectName("pushButton_XSQP")
        self.pushButton_XSZXH = QtWidgets.QPushButton(self.xianshi)
        self.pushButton_XSZXH.setGeometry(QtCore.QRect(1100, 10, 20, 20))
        self.pushButton_XSZXH.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(85, 255, 127);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(58, 176, 86);}\n"
"QPushButton:pressed{background-color: rgb(1, 255, 18);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_XSZXH.setText("")
        self.pushButton_XSZXH.setObjectName("pushButton_XSZXH")
        self.pushButton_XSZXH.clicked.connect(self.aa_pushButton_ZXH)
        self.stackedWidget.addWidget(self.xianshi)
        self.qita = QtWidgets.QWidget()
        self.qita.setObjectName("qita")
        self.label_QTYBJ = QtWidgets.QLabel(self.qita)
        self.label_QTYBJ.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.label_QTYBJ.setStyleSheet("border-image: url(:/new/prefix1/image/bei.png);")
        self.label_QTYBJ.setObjectName("label_QTYBJ")
        self.label_QTYXK = QtWidgets.QLabel(self.qita)
        self.label_QTYXK.setGeometry(QtCore.QRect(340, 200, 541, 141))
        self.label_QTYXK.setStyleSheet("image: url(:/new/prefix1/image/jing.png);")
        self.label_QTYXK.setText("")
        self.label_QTYXK.setObjectName("label_QTYXK")
        self.pushButton_QTGB = QtWidgets.QPushButton(self.qita)
        self.pushButton_QTGB.setGeometry(QtCore.QRect(1160, 10, 20, 20))
        self.pushButton_QTGB.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(255, 94, 19);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(188, 0, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 0, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_QTGB.setText("")
        self.pushButton_QTGB.setObjectName("pushButton_QTGB")
        self.pushButton_QTGB.clicked.connect(self.aa_pushButton_SYGB)
        self.pushButton_QTQP = QtWidgets.QPushButton(self.qita)
        self.pushButton_QTQP.setGeometry(QtCore.QRect(1130, 10, 20, 20))
        self.pushButton_QTQP.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(214, 217, 23);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(191, 191, 0);}\n"
"QPushButton:pressed{background-color: rgb(255, 255, 0);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_QTQP.setText("")
        self.pushButton_QTQP.setObjectName("pushButton_QTQP")
        self.pushButton_QTZXH = QtWidgets.QPushButton(self.qita)
        self.pushButton_QTZXH.setGeometry(QtCore.QRect(1100, 10, 20, 20))
        self.pushButton_QTZXH.setStyleSheet("QPushButton{font-family:Microsoft Yahei;font-size:20pt;color:white;background-color: rgb(85, 255, 127);border-radius:10px;}\n"
"QPushButton:hover{background-color: rgb(58, 176, 86);}\n"
"QPushButton:pressed{background-color: rgb(1, 255, 18);padding-left:3px;padding-top:3px;}\n"
"")
        self.pushButton_QTZXH.setText("")
        self.pushButton_QTZXH.setObjectName("pushButton_QTZXH")
        self.pushButton_QTZXH.clicked.connect(self.aa_pushButton_ZXH)
        self.stackedWidget.addWidget(self.qita)

        self.retranslateUi(zhu)
        self.stackedWidget.setCurrentIndex(0)

        self.directory = ''

        QtCore.QMetaObject.connectSlotsByName(zhu)

    def retranslateUi(self, zhu):
        _translate = QtCore.QCoreApplication.translate
        zhu.setWindowTitle(_translate("zhu", "Form"))
        self.label_SYBJ.setText(_translate("zhu", "TextLabel"))
        self.pushButton_SYGO.setText(_translate("zhu", "GO"))
        self.pushButton_SYDX.setText(_translate("zhu", "单项"))
        self.label_24SKMC.setText(_translate("zhu", "24色卡"))
        self.label_OECFMC.setText(_translate("zhu", "OECF"))
        self.label_XIMENZIMC.setText(_translate("zhu", "西门子星图"))
        self.label_FENBIANLVMC.setText(_translate("zhu", "分辨率"))
        self.label_DNPMC.setText(_translate("zhu", "DNP"))
        self.label_GPGRMC.setText(_translate("zhu", "工频干扰"))
        self.label_HUIJIEMC.setText(_translate("zhu", "灰阶"))
        self.label_DZTMC.setText(_translate("zhu", "点阵图"))
        self.label_KYTMC.setText(_translate("zhu", "枯叶图"))
        self.pushButton.setText(_translate("zhu", "修改"))
        self.pushButton_2.setText(_translate("zhu", "修改"))
        self.pushButton_3.setText(_translate("zhu", "修改"))
        self.pushButton_4.setText(_translate("zhu", "修改"))
        self.pushButton_5.setText(_translate("zhu", "修改"))
        self.pushButton_6.setText(_translate("zhu", "修改"))
        self.pushButton_7.setText(_translate("zhu", "修改"))
        self.pushButton_8.setText(_translate("zhu", "修改"))
        self.pushButton_9.setText(_translate("zhu", "修改"))
        self.pushButton_XXQD.setText(_translate("zhu", "确定"))
        self.label_XXDJS.setText(_translate("zhu", "5"))
        self.label_QTYBJ.setText(_translate("zhu", "TextLabel"))

        ###### 三个按钮事件 ######
        self.pushButton_SYGO.clicked.connect(self.on_pushButton1_clicked)
        self.pushButton_SYGO.clicked.connect(self.on_pushButton1_clicked_1)
        self.pushButton_XXQD.clicked.connect(self.on_pushButton2_clicked)
        self.pushButton_SYDX.clicked.connect(self.on_pushButton3_clicked)

        self.pushButton_SYQP.clicked.connect(self.on_pushButton0_clicked)
        self.pushButton_XXQP.clicked.connect(self.on_pushButton0_clicked)
        self.pushButton_XSQP.clicked.connect(self.on_pushButton0_clicked)
        self.pushButton_QTQP.clicked.connect(self.on_pushButton0_clicked)

        ########label显示#######
        self.labels = [self.label_24SKXS_1, self.label_24SKXS_2, self.label_24SKXS_3, self.label_24SKXS_4,
                       self.label_24SKXS_5, self.label_24SKXS_6, self.label_24SKXS_7]
        self.labelx = [self.label_OECFXS_1, self.label_OECFXS_2, self.label_OECFXS_3, self.label_OECFXS_4,
                       self.label_OECFXS_5, self.label_OECFXS_6, self.label_OECFXS_7]
        self.labely = [self.label_XIMENZIXS_1, self.label_XIMENZIXS_2, self.label_XIMENZIXS_3, self.label_XIMENZIXS_4,
                       self.label_XIMENZIXS_5, self.label_XIMENZIXS_6, self.label_XIMENZIXS_7]
        self.labelz = [self.label_FENBIANLV_1, self.label_FENBIANLV_2, self.label_FENBIANLV_3, self.label_FENBIANLV_4,
                       self.label_FENBIANLV_5, self.label_FENBIANLV_6, self.label_FENBIANLV_7]



    def on_pushButton1_clicked(self):
        # dir_path = QFileDialog.getExistingDirectory(self, "choose directory", r"C:\Users\Administrator\Desktop")
        # file_list = QFileDialog.getOpenFileNames(self, '选择图片', 'D:\\vali_photo', "*.jpg, *.JPG, *.JPEG, All Files(*)")
        # image_manage(file_list)
        # directory = os.path.dirname(dir_path[0].str())

        root = Tk()
        root.withdraw()
        file_list = askopenfilenames()  # 选择要处理的图片,图片地址

        image_manage(file_list)

        self.directory = os.path.dirname(file_list[0])
        # time.sleep(5)
        self.stackedWidget.setCurrentIndex(1)
        # 按钮二：打开第二个面板
        # time.sleep(1)

    def on_pushButton1_clicked_1(self):
        # ---------------------------------显示组1-------------------------------------#
        path = self.directory + "\\" + "colorChecker"
        imgFileList = os.listdir(path)  # 图片列表
        aaa = []
        for filename in imgFileList:
            filepath = os.path.join(path, filename)  # 图片的绝对路径
            if os.path.isdir(filepath):
                print(filepath)
            else:
                if os.path.isfile(filepath) and filename.lower().endswith('.jpg'):
                    # print(os.path.join(path, filename) + ',',end=' ')
                    # print(os.path.join(path, filename) + ',')
                    files = os.path.join(path, filename)
                    aaa.append(files)
                    # print(aaa,end=' ')
                    for i in range(len(aaa)):
                        # print(aaa)
                        jpg = QtGui.QPixmap(aaa[i]).scaled(self.labels[i].width(),
                                                           self.labels[i].height())
                        self.labels[i].setPixmap(jpg)
        # ---------------------------------显示组2-------------------------------------#
        path = path = self.directory + "\\" + "OECF"
        imgFileList = os.listdir(path)  # 图片列表
        aaa = []
        for filename in imgFileList:
            filepath = os.path.join(path, filename)  # 图片的绝对路径
            if os.path.isdir(filepath):
                print(filepath)
            else:
                if os.path.isfile(filepath) and filename.lower().endswith('.jpg'):
                    # print(os.path.join(path, filename) + ',',end=' ')
                    # print(os.path.join(path, filename) + ',')
                    files = os.path.join(path, filename)
                    aaa.append(files)
                    # print(aaa,end=' ')
                    for i in range(len(aaa)):
                        # print(aaa)
                        jpg = QtGui.QPixmap(aaa[i]).scaled(self.labelx[i].width(),
                                                           self.labelx[i].height())
                        self.labelx[i].setPixmap(jpg)
            # ---------------------------------显示组3-------------------------------------#
        path = path = self.directory + "\\" + "siemensStar"
        imgFileList = os.listdir(path)  # 图片列表
        aaa = []
        for filename in imgFileList:
            filepath = os.path.join(path, filename)  # 图片的绝对路径
            if os.path.isdir(filepath):
                print(filepath)
            else:
                if os.path.isfile(filepath) and filename.lower().endswith('.jpg'):
                    # print(os.path.join(path, filename) + ',',end=' ')
                    # print(os.path.join(path, filename) + ',')
                    files = os.path.join(path, filename)
                    aaa.append(files)
                    # print(aaa,end=' ')
                    for i in range(len(aaa)):
                        # print(aaa)
                        jpg = QtGui.QPixmap(aaa[i]).scaled(self.labely[i].width(),
                                                           self.labely[i].height())
                        self.labely[i].setPixmap(jpg)
            # ---------------------------------显示组4-------------------------------------#
        path = path = self.directory + "\\" + "tvLine"
        imgFileList = os.listdir(path)  # 图片列表
        aaa = []
        for filename in imgFileList:
            filepath = os.path.join(path, filename)  # 图片的绝对路径
            if os.path.isdir(filepath):
                print(filepath)
            else:
                if os.path.isfile(filepath) and filename.lower().endswith('.jpg'):
                    files = os.path.join(path, filename)
                    aaa.append(files)
                    for i in range(len(aaa)):
                        jpg = QtGui.QPixmap(aaa[i]).scaled(self.labelz[i].width(),self.labelz[i].height())
                        self.labelz[i].setPixmap(jpg)

    def on_pushButton2_clicked(self):
        self.stackedWidget.setCurrentIndex(2)
        # 按钮三：打开第三个面板

    def on_pushButton3_clicked(self):
        self.stackedWidget.setCurrentIndex(3)

    def on_pushButton0_clicked(self):
        self.stackedWidget.setCurrentIndex(0)

    def aa_pushButton_ZXH(self):
            """
            最小化窗口
            """
            self.showMinimized()

    def mousePressEvent(self, event):
            if event.button() == Qt.LeftButton:
                    self.m_flag = True
                    self.m_Position = event.globalPos() - self.pos()  # 获取鼠标相对窗口的位置
                    event.accept()

    def mouseMoveEvent(self, QMouseEvent):
            if Qt.LeftButton and self.m_flag:
                    self.move(QMouseEvent.globalPos() - self.m_Position)  # 更改窗口位置
                    QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):
            self.m_flag = False
            self.setCursor(QCursor(Qt.ArrowCursor))

    def aa_pushButton_SYGB(self):
            exit(0)


import image_rc
